### ISSUE TITLE
Cannot find module 'OnScreen'

### ISSUE THREAD

**Issue by steveluo** [silvestreh/onScreen#34]
Hi,
I installed onScreen using below command successfully:
```
npm install onscreen --save
```
But I failed to bundle onScreen with babel.
The error is:
```
Error: Cannot find module 'OnScreen'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (gulpfile.babel.js:23:1)
    at Module._compile (module.js:541:32)
    at loader (/Users/zhenyu/Development/nodetest/frontend/node_modules/babel-register/lib/node.js:158:5)
```
and below is my usage, the same as the README:
```
import OnScreen from 'OnScreen';
```

**Comment by silvestreh** [comment]
module name is `onscreen`. all lowercase. the README is wrong about it, I'll update it ASAP.

**Comment by steveluo** [comment]
Hi silvestreh,

Thank you for the prompt reply.  But change to ```onscreen``` doesn't help.

**Comment by silvestreh** [comment]
That's odd… which module bundler are you using? I see that you're using Babel, right?

**Comment by steveluo** [comment]
Yes, I'm using babel and gulp.

**Comment by silvestreh** [comment]
And which module bundler? Browserify, Webpack?

**Comment by steveluo** [comment]
I'm using browserify. Do you need I create a demo project?

**Comment by silvestreh** [comment]
Nah, I'll setup one for me. Thanks

**Comment by steveluo** [comment]
Thank you so much for looking into this.

**Comment by silvestreh** [comment]
I'm afraid I was unable to reproduce it. But I added a Browserify demo that uses Gulp and Babelify. [check it out](https://github.com/silvestreh/onScreen/tree/master/demos/browserify-with-babel-and-gulp).

**Comment by steveluo** [comment]
It is so strange. I cloned the project and run run gulp, the error is:
```
{ [Error: Couldn't find preset "es2015" relative to directory "/Users/zhenyu/temp/screen/demos/browserify-with-babel-and-gulp" while parsing file: /Users/zhenyu/temp/screen/demos/browserify-with-babel-and-gulp/src/main.js]
  filename: '/Users/zhenyu/temp/screen/demos/browserify-with-babel-and-gulp/src/main.js',
```
So I added babel-preset-es2015 to package.json and run gulp again but still failed with below log:
```
{ Error: Cannot find module 'onscreen' from '/Users/zhenyu/temp/screen/demos/browserify-with-babel-and-gulp/src'
    at /Users/zhenyu/temp/screen/demos/browserify-with-babel-and-gulp/node_modules/resolve/lib/async.js:46:17
    at process (/Users/zhenyu/temp/screen/demos/browserify-with-babel-and-gulp/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/zhenyu/temp/screen/demos/browserify-with-babel-and-gulp/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/zhenyu/temp/screen/demos/browserify-with-babel-and-gulp/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/zhenyu/temp/screen/demos/browserify-with-babel-and-gulp/node_modules/resolve/lib/async.js:92:31)
    at /Users/zhenyu/temp/screen/demos/browserify-with-babel-and-gulp/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:117:15)
  stream:
   Labeled {
     _readableState:
      ReadableState {
        objectMode: true,
        highWaterMark: 16,
        buffer: [],
        length: 0,
        pipes: [Object],
        pipesCount: 1,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     domain: null,
     _events:
      { end: [Object],
        error: [Object],
        data: [Function: ondata],
        _mutate: [Object] },
     _eventsCount: 4,
     _maxListeners: undefined,
     _writableState:
      WritableState {
        objectMode: true,
        highWaterMark: 16,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: false,
     allowHalfOpen: true,
     _options: { objectMode: true },
     _wrapOptions: { objectMode: true },
     _streams: [ [Object] ],
     length: 1,
     label: 'deps' } }
```

My node version is v5.11.1, I also tested with 6.1.0.

**Comment by silvestreh** [comment]
Hmmm… strange… could you share your `package.json` and `gulpfile.js` with me?

**Comment by silvestreh** [comment]
just a quick headsup: I moved the demo project to their own [repository](https://github.com/silvestreh/onScreen-demo/).

**Comment by steveluo** [comment]
I found the problem now. This issue is caused by below lines in your package.json:
```
"main": "dist/onScreen.umd.js",
"jsnext:main": "dist/onScreen.es6.js",
```
Actually, in dist directory, the file is ```OnScreen.umd.js```. Linux and my mac are both case-sensitive, that is why I encountered the problem.

So please fix the case and republish it. Thank you!

**Comment by silvestreh** [comment]
Will do! I'll use lisp-case… I actually fixed this very same issue with the source files but I absolutely forgot to do the same for the built library. Silly me.

BTW, I'm also using a mac. Mine's running Yosemite 10.10.5.

**Comment by silvestreh** [comment]
@steveluo done! just pushed 1.1.3.

**Comment by steveluo** [comment]
@silvestreh  I can confirm that the issue is fixed and you can close this issue now! Thank you so much for the help! 👍 👍 👍

**Comment by silvestreh** [comment]
No problem! Thank **you** for pointing it out!
